<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Elegant extends Model
{

    public function save(array $options = [])
    {
        //LOGS
        if(!$this->id) {
            $logs = new Logs();
            $logs->idusuario = \Auth::user()->id;
            $logs->tabela = $this->table;
            $logs->tipo = 'inserir';
            $logs->antes = json_encode([]);
            $logs->depois = json_encode($this->toArray());
            $logs->save();
        }

        return parent::save($options); // TODO: Change the autogenerated stub
    }

    public function update(array $attributes = [], array $options = [])
    {
        //LOGS
        $logs = new Logs();
        $logs->idusuario = \Auth::user()->id;
        $logs->tabela = $this->table;
        $logs->tipo = 'alterar';
        $logs->antes = json_encode($this->getOriginal());

        $return = parent::update($attributes, $options);

        $logs->depois = json_encode($this->toArray());
        $logs->save();

        return $return;// TODO: Change the autogenerated stub
    }

    public function delete()
    {
        //LOGS
        $logs = new Logs();
        $logs->idusuario = \Auth::user()->id;
        $logs->tabela = $this->table;
        $logs->tipo = 'excluir';
        $logs->antes = json_encode($this->toArray());
        $logs->depois = json_encode([]);
        $logs->save();

        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
